# Generated by Django 2.2.5 on 2019-09-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='heading',
            new_name='headings',
        ),
    ]
