# Generated by Django 2.2.5 on 2019-09-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
